### ISSUE TITLE
Failed to transcribe testaudio.mp3: invalid syntax (client.py, line 233)

### ISSUE THREAD

**Issue by cnra** [abdnh/anki-asr#3]
Hi,

I recently installed the anki-asr add-on on Anki ⁨24.06.3 (d678e393)⁩. When I try to use it from the editor, I encounter the following error:

![image](https://github.com/user-attachments/assets/e1fe52ef-8295-4a9f-b44c-e8944f4bc2c2)

```
Failed to transcribe Tatoeba arh sentence EngID 2313720 SpaID 3953850.mp3: invalid syntax (client.py, line 233)
```

![image](https://github.com/user-attachments/assets/33d41374-df6f-48fb-8dc3-f4edb7b61b82)

I couldn’t locate any detailed logs to share. Please let me know if additional logs are needed and how to obtain them.

Thank you!

**Comment by abdnh** [comment]
Thank you for the report. Will release a fix for this today.
